version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  graphql-server:
    build: ./backend/graphql-server
    ports:
      - 8080:8080
    environment:
      DB_URL: mongodb://database/benderwatch
  database: 
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - benderwatch:/data/database
volumes:
  benderwatch: